[package]
name = "ruinsofatlantis"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytemuck = { version = "1.23.2", features = ["derive"] }
env_logger = "0.11.8"
glam = "0.30.8"
gltf = { version = "1.4.1", features = ["import"] }
log = "0.4.28"
pollster = "0.4.0"
rand = "0.9.2"
rand_chacha = "0.9.0"
wgpu = "26.0.1"
which = "8.0.0"
winit = "0.30.12"
