[package]
name = "ruinsofatlantis"
version = "0.1.0"
edition = "2024"
default-run = "ruinsofatlantis"

[dependencies]
ab_glyph = "0.2.25"
anyhow = "1.0.100"
base64 = "0.22.1"
bevy = "0.14"
bytemuck = { version = "1.23.2", features = ["derive"] }
dcv-color-primitives = "0.7.0"
draco = "0.1.2"
draco_decoder = "0.0.10"
env_logger = "0.11.8"
glam = "0.30.8"
gltf = { version = "1.4.1", features = ["import", "extensions"] }
image = "0.25"
log = "0.4.28"
pollster = "0.4.0"
rand = "0.9.2"
rand_chacha = "0.9.0"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
wgpu = "26.0.1"
which = "8.0.0"
winit = "0.30.12"
