[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/RustSec/advisory-db"]
vulnerability = "deny"
unsound = "deny"
# Treat these advisory categories as informational warnings rather than failures.
# This syntax is compatible across recent cargo-deny versions.
informational = ["unmaintained", "yanked", "notice"]
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
deny = []
skip = []

[licenses]
unlicensed = "deny"
allow = ["Apache-2.0", "MIT", "BSD-3-Clause", "ISC", "Zlib"]
deny = []
copyleft = "warn"
allow-osi-fsf-free = "either"

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-git = []
