[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/RustSec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
deny = []
skip = []

[licenses]
unlicensed = "deny"
allow = ["Apache-2.0", "MIT", "BSD-3-Clause", "ISC", "Zlib"]
deny = []
copyleft = "warn"
allow-osi-fsf-free = "either"

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-git = []
