# cargo-deny configuration (baseline)

[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
severity-threshold = "medium"

[bans]
multiple-versions = "warn"
wildcards = "allow"
deny = []
skip = []

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow = [
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "Unicode-DFS-2016",
    "MPL-2.0",
    "CC0-1.0",
]
exceptions = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

