[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
data_runtime = { path = "../crates/data_runtime", version = "0.1.0" }

