//! GLTF loading: unskinned CPU mesh and Draco JSON fallback.

use anyhow::{Context, Result, anyhow, bail};
use base64::Engine as _;
use base64::engine::general_purpose::STANDARD as BASE64;
use gltf::mesh::util::ReadIndices;
use std::path::Path;

#[cfg(not(target_arch = "wasm32"))]
use std::path::PathBuf;

use crate::types::{CpuMesh, Vertex};

/// Load a `.gltf`/`.glb` mesh. On wasm we embed known assets and, for glTF+Draco,
/// parse JSON directly and decode Draco from data URIs to avoid filesystem I/O.
pub fn load_gltf_mesh(path: &Path) -> Result<CpuMesh> {
    #[cfg(target_arch = "wasm32")]
    {
        let p = path.to_string_lossy();
        if p.contains("assets/models/ruins.gltf") {
            // Prefer pre‑decompressed glTF on wasm (generated by tools/gltf-decompress)
            let bytes: &'static [u8] =
                include_bytes!("../../../assets/models/ruins.decompressed.gltf");
            let (doc, buffers, _images) =
                gltf::import_slice(bytes).context("import glTF (ruins.decompressed.gltf slice)")?;
            merge_doc_to_cpu(&doc, &buffers)
        } else if p.contains("assets/models/rock.glb") {
            let bytes: &'static [u8] = include_bytes!("../../../assets/models/rock.glb");
            let (doc, buffers, _images) =
                gltf::import_slice(bytes).context("import glTF (rock.glb slice)")?;
            merge_doc_to_cpu(&doc, &buffers)
        } else if p.contains("assets/models/trees/CommonTree_3/CommonTree_3.gltf") {
            let bytes: &'static [u8] =
                include_bytes!("../../../assets/models/trees/CommonTree_3/CommonTree_3.gltf");
            let (doc, buffers, _images) =
                gltf::import_slice(bytes).context("import glTF (CommonTree_3.gltf slice)")?;
            merge_doc_to_cpu(&doc, &buffers)
        } else if p.contains("assets/trees/Birch_4GLB.glb") {
            let bytes: &'static [u8] = include_bytes!("../../../assets/trees/Birch_4GLB.glb");
            let (doc, buffers, _images) =
                gltf::import_slice(bytes).context("import glTF (Birch_4GLB.glb slice)")?;
            merge_doc_to_cpu(&doc, &buffers)
        } else {
            anyhow::bail!("wasm: unsupported static glTF path: {}", p);
        }
    }
    #[cfg(not(target_arch = "wasm32"))]
    {
        let (doc, buffers, _images) = {
            let source_path: PathBuf = path.to_path_buf();
            match gltf::import(&source_path) {
                Ok(ok) => ok,
                Err(e) => {
                    // Try the JSON/Draco fallback path (handles extensionsRequired + no bufferViews)
                    if let Ok(mesh) = try_load_gltf_draco_json(path) {
                        return Ok(mesh);
                    }
                    return Err(
                        anyhow!("failed to import glTF: {}", source_path.display()).context(e)
                    );
                }
            }
        };
        merge_doc_to_cpu(&doc, &buffers)
    }
}

/// Split mesh loader for wasm that separates OPAQUE vs MASK primitives so callers can
/// tint bark/leaves differently without relying on external textures.
///
/// Returns vertices (pos+nrm) and two index lists: (opaque_indices, mask_indices).
#[cfg(target_arch = "wasm32")]
pub fn load_gltf_mesh_split(path: &Path) -> Result<(Vec<Vertex>, Vec<u16>, Vec<u16>)> {
    let p = path.to_string_lossy();
    // Helper to build verts/indices from a gltf::import_slice result, splitting by material alpha
    let from_doc = |doc: &gltf::Document,
                    buffers: &Vec<gltf::buffer::Data>,
                    images_opt: Option<&Vec<gltf::image::Data>>|
     -> Result<(Vec<Vertex>, Vec<u16>, Vec<u16>)> {
        let mut verts: Vec<Vertex> = Vec::new();
        let mut idx_opaque: Vec<u16> = Vec::new();
        let mut idx_mask: Vec<u16> = Vec::new();
        let images = images_opt;
        for mesh in doc.meshes() {
            for prim in mesh.primitives() {
                let reader = prim.reader(|b| buffers.get(b.index()).map(|bb| bb.0.as_slice()));
                let pos = reader
                    .read_positions()
                    .map(|it| it.collect::<Vec<_>>())
                    .unwrap_or_default();
                let nrm = reader
                    .read_normals()
                    .map(|it| it.collect::<Vec<_>>())
                    .unwrap_or_else(|| vec![[0.0, 1.0, 0.0]; pos.len()]);
                let base = verts.len() as u32;
                for i in 0..pos.len() {
                    verts.push(Vertex {
                        pos: pos[i],
                        nrm: nrm[i],
                    });
                }
                let idx_u32: Vec<u32> = match reader.read_indices() {
                    Some(gltf::mesh::util::ReadIndices::U16(it)) => it.map(|v| v as u32).collect(),
                    Some(gltf::mesh::util::ReadIndices::U32(it)) => it.collect(),
                    Some(gltf::mesh::util::ReadIndices::U8(it)) => it.map(|v| v as u32).collect(),
                    None => (0..pos.len() as u32).collect(),
                };
                let is_mask = matches!(
                    prim.material().alpha_mode(),
                    gltf::material::AlphaMode::Mask
                );
                let out = if is_mask {
                    &mut idx_mask
                } else {
                    &mut idx_opaque
                };
                for v in idx_u32 {
                    let rb = v + base;
                    if rb <= u16::MAX as u32 {
                        out.push(rb as u16);
                    }
                }
                let _ = images; // reserved for future texture plumbing
            }
        }
        Ok((verts, idx_opaque, idx_mask))
    };

    // 1) Self-contained GLB (Birch) via include_bytes
    if p.contains("assets/trees/Birch_4GLB.glb") {
        let bytes: &'static [u8] = include_bytes!("../../../assets/trees/Birch_4GLB.glb");
        let (doc, buffers, images) =
            gltf::import_slice(bytes).context("import glTF (birch glb)")?;
        return from_doc(&doc, &buffers, Some(&images));
    }
    // 2) CommonTree_3.gltf is embedded and self-contained
    if p.contains("assets/models/trees/CommonTree_3/CommonTree_3.gltf") {
        let bytes: &'static [u8] =
            include_bytes!("../../../assets/models/trees/CommonTree_3/CommonTree_3.gltf");
        let (doc, buffers, images) =
            gltf::import_slice(bytes).context("import glTF (CommonTree_3.gltf slice)")?;
        return from_doc(&doc, &buffers, Some(&images));
    }
    // 3) Quaternius GiantPine_2.gltf + external .bin (embedded)
    if p.contains("assets/trees/quaternius/glTF/GiantPine_2.gltf") {
        let json_bytes: &'static [u8] =
            include_bytes!("../../../assets/trees/quaternius/glTF/GiantPine_2.gltf");
        let bin_bytes: &'static [u8] =
            include_bytes!("../../../assets/trees/quaternius/glTF/GiantPine_2.bin");
        let text = std::str::from_utf8(json_bytes).context("giantpine gltf not utf8")?;
        let v: serde_json::Value = serde_json::from_str(text).context("parse giantpine gltf")?;
        // Build lookup tables
        let accessors = v
            .get("accessors")
            .and_then(|x| x.as_array())
            .context("accessors missing")?;
        let views = v
            .get("bufferViews")
            .and_then(|x| x.as_array())
            .context("bufferViews missing")?;
        let empty_vec: &'static Vec<serde_json::Value> = Box::leak(Box::new(Vec::new()));
        let materials = v
            .get("materials")
            .and_then(|x| x.as_array())
            .unwrap_or(empty_vec);
        let meshes = v
            .get("meshes")
            .and_then(|x| x.as_array())
            .context("meshes missing")?;
        let mut verts: Vec<Vertex> = Vec::new();
        let mut idx_opaque: Vec<u16> = Vec::new();
        let mut idx_mask: Vec<u16> = Vec::new();
        for mesh in meshes {
            let prims = mesh
                .get("primitives")
                .and_then(|p| p.as_array())
                .unwrap_or(empty_vec);
            for prim in prims {
                let attrs = prim
                    .get("attributes")
                    .and_then(|a| a.as_object())
                    .context("primitive.attributes missing")?;
                let pos_acc_idx = attrs
                    .get("POSITION")
                    .and_then(|i| i.as_u64())
                    .context("POSITION accessor missing")?
                    as usize;
                let nrm_acc_idx = attrs
                    .get("NORMAL")
                    .and_then(|i| i.as_u64())
                    .unwrap_or(pos_acc_idx as u64) as usize;
                let pos_acc = &accessors[pos_acc_idx];
                let nrm_acc = &accessors[nrm_acc_idx];
                let vertex_count = pos_acc
                    .get("count")
                    .and_then(|c| c.as_u64())
                    .context("POSITION.count missing")? as usize;
                // Read positions
                let pv_idx = pos_acc
                    .get("bufferView")
                    .and_then(|b| b.as_u64())
                    .context("pos bufferView missing")? as usize;
                let pn = &views[pv_idx];
                let poff = pn.get("byteOffset").and_then(|b| b.as_u64()).unwrap_or(0) as usize;
                let plen = pn
                    .get("byteLength")
                    .and_then(|b| b.as_u64())
                    .context("pos byteLength missing")? as usize;
                let pbytes = &bin_bytes[poff..poff + plen];
                // Read normals
                let nv_idx = nrm_acc
                    .get("bufferView")
                    .and_then(|b| b.as_u64())
                    .context("nrm bufferView missing")? as usize;
                let nn = &views[nv_idx];
                let noff = nn.get("byteOffset").and_then(|b| b.as_u64()).unwrap_or(0) as usize;
                let nlen = nn
                    .get("byteLength")
                    .and_then(|b| b.as_u64())
                    .context("nrm byteLength missing")? as usize;
                let nbytes = &bin_bytes[noff..noff + nlen];
                let base = verts.len() as u32;
                // positions: tightly packed float32 VEC3
                for i in 0..vertex_count {
                    let pi = i * 12; // 3*f32
                    let x = f32::from_le_bytes(pbytes[pi..pi + 4].try_into().unwrap());
                    let y = f32::from_le_bytes(pbytes[pi + 4..pi + 8].try_into().unwrap());
                    let z = f32::from_le_bytes(pbytes[pi + 8..pi + 12].try_into().unwrap());
                    let ni = i * 12;
                    let nx = f32::from_le_bytes(nbytes[ni..ni + 4].try_into().unwrap());
                    let ny = f32::from_le_bytes(nbytes[ni + 4..ni + 8].try_into().unwrap());
                    let nz = f32::from_le_bytes(nbytes[ni + 8..ni + 12].try_into().unwrap());
                    verts.push(Vertex {
                        pos: [x, y, z],
                        nrm: [nx, ny, nz],
                    });
                }
                // Indices
                let idx_acc_idx =
                    prim.get("indices")
                        .and_then(|i| i.as_u64())
                        .context("indices accessor missing")? as usize;
                let idx_acc = &accessors[idx_acc_idx];
                let iv_idx = idx_acc
                    .get("bufferView")
                    .and_then(|b| b.as_u64())
                    .context("idx bufferView missing")? as usize;
                let in_ = &views[iv_idx];
                let ioff = in_.get("byteOffset").and_then(|b| b.as_u64()).unwrap_or(0) as usize;
                let ilen = in_
                    .get("byteLength")
                    .and_then(|b| b.as_u64())
                    .context("idx byteLength missing")? as usize;
                let ibytes = &bin_bytes[ioff..ioff + ilen];
                let count = idx_acc
                    .get("count")
                    .and_then(|c| c.as_u64())
                    .context("idx count missing")? as usize;
                let mut out = &mut idx_opaque;
                if let Some(mat_i) = prim.get("material").and_then(|m| m.as_u64()) {
                    if let Some(mat) = materials.get(mat_i as usize) {
                        let alpha = mat
                            .get("alphaMode")
                            .and_then(|a| a.as_str())
                            .unwrap_or("OPAQUE");
                        if alpha.eq_ignore_ascii_case("MASK") {
                            out = &mut idx_mask;
                        }
                    }
                }
                // indices are u16 in this asset
                for i in 0..count {
                    let off = i * 2;
                    let v = u16::from_le_bytes([ibytes[off], ibytes[off + 1]]) as u32;
                    let rb = v + base;
                    if rb <= u16::MAX as u32 {
                        out.push(rb as u16);
                    }
                }
            }
        }
        return Ok((verts, idx_opaque, idx_mask));
    }
    bail!("wasm split loader: unsupported path: {}", p)
}

#[allow(dead_code)]
fn try_load_gltf_draco_json(path: &Path) -> Result<CpuMesh> {
    let text = std::fs::read_to_string(path)
        .with_context(|| format!("read glTF json: {}", path.display()))?;
    let v: serde_json::Value = serde_json::from_str(&text).context("parse glTF JSON")?;
    let empty = Vec::new();
    let ext_req = v
        .get("extensionsRequired")
        .and_then(|x| x.as_array())
        .unwrap_or(&empty);
    let has_draco = ext_req
        .iter()
        .any(|s| s.as_str() == Some("KHR_draco_mesh_compression"));
    if !has_draco {
        bail!("JSON fallback: no KHR_draco_mesh_compression present");
    }

    // Decode buffers (support only data: URIs here)
    let buffers = v
        .get("buffers")
        .and_then(|b| b.as_array())
        .context("buffers missing")?;
    let mut bin_bytes: Vec<Vec<u8>> = Vec::new();
    for b in buffers {
        let uri = b
            .get("uri")
            .and_then(|u| u.as_str())
            .context("buffer.uri missing")?;
        if let Some(idx) = uri.find(',') {
            let b64 = &uri[(idx + 1)..];
            let data = BASE64
                .decode(b64.as_bytes())
                .context("base64 decode buffer")?;
            bin_bytes.push(data);
        } else {
            bail!("only data: URIs are supported in JSON fallback");
        }
    }

    let views = v
        .get("bufferViews")
        .and_then(|x| x.as_array())
        .context("bufferViews missing")?;
    let accessors = v
        .get("accessors")
        .and_then(|x| x.as_array())
        .context("accessors missing")?;
    let meshes = v
        .get("meshes")
        .and_then(|x| x.as_array())
        .context("meshes missing")?;

    let mut vertices: Vec<Vertex> = Vec::new();
    let mut indices: Vec<u16> = Vec::new();

    for mesh in meshes {
        let empty_p = Vec::new();
        let prims = mesh
            .get("primitives")
            .and_then(|p| p.as_array())
            .unwrap_or(&empty_p);
        for prim in prims {
            let ext = prim
                .get("extensions")
                .and_then(|e| e.get("KHR_draco_mesh_compression"));
            if ext.is_none() {
                continue;
            }
            let ext = ext.unwrap();
            let bv_index = ext
                .get("bufferView")
                .and_then(|b| b.as_u64())
                .context("draco bufferView missing")? as usize;
            let attr_map = ext
                .get("attributes")
                .and_then(|a| a.as_object())
                .context("draco attributes missing")?;

            let bv = &views[bv_index];
            let buf_index = bv.get("buffer").and_then(|b| b.as_u64()).unwrap_or(0) as usize;
            let byte_offset = bv.get("byteOffset").and_then(|b| b.as_u64()).unwrap_or(0) as usize;
            let byte_length = bv
                .get("byteLength")
                .and_then(|b| b.as_u64())
                .context("byteLength missing")? as usize;
            let data = &bin_bytes[buf_index][byte_offset..byte_offset + byte_length];

            // Vertex/index counts & attribute dims/types
            let attrs = prim
                .get("attributes")
                .and_then(|a| a.as_object())
                .context("primitive.attributes missing")?;
            let pos_acc_idx = attrs
                .get("POSITION")
                .and_then(|i| i.as_u64())
                .context("POSITION accessor missing")? as usize;
            let pos_acc = &accessors[pos_acc_idx];
            let vertex_count = pos_acc
                .get("count")
                .and_then(|c| c.as_u64())
                .context("POSITION.count missing")? as u32;
            let index_count = prim
                .get("indices")
                .and_then(|i| i.as_u64())
                .map(|idx| {
                    accessors[idx as usize]
                        .get("count")
                        .and_then(|c| c.as_u64())
                        .unwrap_or(0) as u32
                })
                .unwrap_or(0);

            let mut cfg = draco_decoder::MeshDecodeConfig::new(vertex_count, index_count);
            // Build mapping sorted by attribute id
            let mut mapped: Vec<(u32, (&str, usize))> = Vec::new();
            for (k, idv) in attr_map.iter() {
                if let Some(id) = idv.as_u64() {
                    let acc_idx = attrs.get(k).and_then(|i| i.as_u64()).unwrap_or(0) as usize;
                    mapped.push((id as u32, (k.as_str(), acc_idx)));
                }
            }
            mapped.sort_by_key(|(id, _)| *id);

            for (_, (sem_name, acc_idx)) in &mapped {
                let acc = &accessors[*acc_idx];
                let dims = acc.get("type").and_then(|t| t.as_str()).unwrap_or("VEC3");
                let dim = match dims {
                    "SCALAR" => 1,
                    "VEC2" => 2,
                    "VEC3" => 3,
                    "VEC4" => 4,
                    _ => 3,
                };
                let ctype = acc
                    .get("componentType")
                    .and_then(|c| c.as_u64())
                    .unwrap_or(5126);
                let ty = match ctype {
                    5126 => draco_decoder::AttributeDataType::Float32,
                    5123 => draco_decoder::AttributeDataType::UInt16,
                    5121 => draco_decoder::AttributeDataType::UInt8,
                    5122 => draco_decoder::AttributeDataType::Int16,
                    5120 => draco_decoder::AttributeDataType::Int8,
                    5125 => draco_decoder::AttributeDataType::UInt32,
                    _ => draco_decoder::AttributeDataType::Float32,
                };
                cfg.add_attribute(dim as u32, ty);
                let _ = sem_name;
            }

            let decoded = pollster::block_on(draco_decoder::decode_mesh(data, &cfg))
                .context("draco native decode failed")?;

            let mut off = 0usize;
            let idx_bytes = if index_count <= u16::MAX as u32 {
                (index_count as usize) * 2
            } else {
                (index_count as usize) * 4
            };
            if idx_bytes > 0 {
                let idx_slice = &decoded[off..off + idx_bytes];
                off += idx_bytes;
                if index_count <= u16::MAX as u32 {
                    for c in idx_slice.chunks_exact(2) {
                        indices.push(u16::from_le_bytes([c[0], c[1]]));
                    }
                } else {
                    for c in idx_slice.chunks_exact(4) {
                        let v = u32::from_le_bytes([c[0], c[1], c[2], c[3]]);
                        indices.push(
                            u16::try_from(v)
                                .map_err(|_| anyhow!("decoded index {} exceeds u16", v))?,
                        );
                    }
                }
            }

            // Now parse attributes in mapped order; grab POSITION/NORMAL only
            let mut pos_opt: Option<Vec<[f32; 3]>> = None;
            let mut nrm_opt: Option<Vec<[f32; 3]>> = None;
            for (_, (sem_name, acc_idx)) in &mapped {
                let acc = &accessors[*acc_idx];
                let dims = acc.get("type").and_then(|t| t.as_str()).unwrap_or("VEC3");
                let dim = match dims {
                    "SCALAR" => 1usize,
                    "VEC2" => 2usize,
                    "VEC3" => 3usize,
                    "VEC4" => 4usize,
                    _ => 3usize,
                };
                let ctype = acc
                    .get("componentType")
                    .and_then(|c| c.as_u64())
                    .unwrap_or(5126);
                let comp_size = match ctype {
                    5124..=5126 => 4usize,
                    5123 | 5122 => 2usize,
                    5121 | 5120 => 1usize,
                    _ => 4usize,
                };
                let byte_len = dim * (vertex_count as usize) * comp_size;
                let slice = &decoded[off..off + byte_len];
                off += byte_len;

                match (*sem_name, ctype) {
                    ("POSITION", 5126) => {
                        let mut v = Vec::with_capacity(vertex_count as usize);
                        for c in slice.chunks_exact(4 * dim) {
                            let x = f32::from_le_bytes([c[0], c[1], c[2], c[3]]);
                            let y = f32::from_le_bytes([c[4], c[5], c[6], c[7]]);
                            let z = if dim > 2 {
                                f32::from_le_bytes([c[8], c[9], c[10], c[11]])
                            } else {
                                0.0
                            };
                            v.push([x, y, z]);
                        }
                        pos_opt = Some(v);
                    }
                    ("NORMAL", 5126) => {
                        let mut v = Vec::with_capacity(vertex_count as usize);
                        for c in slice.chunks_exact(4 * dim) {
                            let x = f32::from_le_bytes([c[0], c[1], c[2], c[3]]);
                            let y = f32::from_le_bytes([c[4], c[5], c[6], c[7]]);
                            let z = if dim > 2 {
                                f32::from_le_bytes([c[8], c[9], c[10], c[11]])
                            } else {
                                1.0
                            };
                            v.push([x, y, z]);
                        }
                        nrm_opt = Some(v);
                    }
                    _ => {}
                }
            }

            let start = vertices.len();
            let pos = pos_opt.context("decoded POSITION missing")?;
            let nrm = nrm_opt.unwrap_or_else(|| vec![[0.0, 1.0, 0.0]; pos.len()]);
            for i in 0..pos.len() {
                vertices.push(Vertex {
                    pos: pos[i],
                    nrm: nrm[i],
                });
            }
            // Rebase indices for this primitive
            let start_u = start as u32;
            if index_count == 0 {
                for i in 0..(pos.len() as u32) {
                    indices.push((start_u + i) as u16);
                }
            } else {
                let base = indices.len() - (index_count as usize);
                for item in indices.iter_mut().skip(base) {
                    let v = *item as u32 + start_u;
                    *item =
                        u16::try_from(v).map_err(|_| anyhow!("rebased index {} exceeds u16", v))?;
                }
            }
        }
    }

    if vertices.is_empty() || indices.is_empty() {
        bail!("JSON fallback: no geometry decoded in {}", path.display());
    }
    Ok(CpuMesh { vertices, indices })
}

#[cfg(target_arch = "wasm32")]
#[allow(dead_code)]
fn try_load_gltf_draco_json_slice(bytes: &[u8]) -> Result<CpuMesh> {
    let text = std::str::from_utf8(bytes).context("ruins.gltf bytes not UTF-8")?;
    let v: serde_json::Value = serde_json::from_str(text).context("parse glTF JSON")?;
    // The rest mirrors `try_load_gltf_draco_json`, but without filesystem reads.
    let empty = Vec::new();
    let ext_req = v
        .get("extensionsRequired")
        .and_then(|x| x.as_array())
        .unwrap_or(&empty);
    let has_draco = ext_req
        .iter()
        .any(|s| s.as_str() == Some("KHR_draco_mesh_compression"));
    if !has_draco {
        bail!("JSON slice: no KHR_draco_mesh_compression present");
    }

    // Decode buffers (support only data: URIs)
    let buffers = v
        .get("buffers")
        .and_then(|b| b.as_array())
        .context("buffers missing")?;
    let mut bin_bytes: Vec<Vec<u8>> = Vec::new();
    for b in buffers {
        let uri = b
            .get("uri")
            .and_then(|u| u.as_str())
            .context("buffer.uri missing")?;
        if let Some(idx) = uri.find(',') {
            let b64 = &uri[(idx + 1)..];
            let data = BASE64
                .decode(b64.as_bytes())
                .context("base64 decode buffer")?;
            bin_bytes.push(data);
        } else {
            bail!("only data: URIs are supported in JSON slice fallback");
        }
    }

    let views = v
        .get("bufferViews")
        .and_then(|x| x.as_array())
        .context("bufferViews missing")?;
    let accessors = v
        .get("accessors")
        .and_then(|x| x.as_array())
        .context("accessors missing")?;
    let meshes = v
        .get("meshes")
        .and_then(|x| x.as_array())
        .context("meshes missing")?;

    let mut vertices: Vec<Vertex> = Vec::new();
    let mut indices: Vec<u16> = Vec::new();

    for mesh in meshes {
        let empty_p = Vec::new();
        let prims = mesh
            .get("primitives")
            .and_then(|p| p.as_array())
            .unwrap_or(&empty_p);
        for prim in prims {
            let ext = prim
                .get("extensions")
                .and_then(|e| e.get("KHR_draco_mesh_compression"));
            if ext.is_none() {
                continue;
            }
            let ext = ext.unwrap();
            let bv_index = ext
                .get("bufferView")
                .and_then(|b| b.as_u64())
                .context("draco bufferView missing")? as usize;
            let attr_map = ext
                .get("attributes")
                .and_then(|a| a.as_object())
                .context("draco attributes missing")?;

            let bv = &views[bv_index];
            let buf_index = bv.get("buffer").and_then(|b| b.as_u64()).unwrap_or(0) as usize;
            let byte_offset = bv.get("byteOffset").and_then(|b| b.as_u64()).unwrap_or(0) as usize;
            let byte_length = bv
                .get("byteLength")
                .and_then(|b| b.as_u64())
                .context("byteLength missing")? as usize;
            let data = &bin_bytes[buf_index][byte_offset..byte_offset + byte_length];

            // Vertex/index counts & attribute dims/types
            let attrs = prim
                .get("attributes")
                .and_then(|a| a.as_object())
                .context("primitive.attributes missing")?;
            let pos_acc_idx = attrs
                .get("POSITION")
                .and_then(|i| i.as_u64())
                .context("POSITION accessor missing")? as usize;
            let pos_acc = &accessors[pos_acc_idx];
            let vertex_count = pos_acc
                .get("count")
                .and_then(|c| c.as_u64())
                .context("POSITION.count missing")? as u32;
            let index_count = prim
                .get("indices")
                .and_then(|i| i.as_u64())
                .map(|idx| {
                    accessors[idx as usize]
                        .get("count")
                        .and_then(|c| c.as_u64())
                        .unwrap_or(0) as u32
                })
                .unwrap_or(0);

            let mut cfg = draco_decoder::MeshDecodeConfig::new(vertex_count, index_count);
            // Build mapping sorted by attribute id
            let mut mapped: Vec<(u32, (&str, usize))> = Vec::new();
            for (k, idv) in attr_map.iter() {
                if let Some(id) = idv.as_u64() {
                    let acc_idx = attrs.get(k).and_then(|i| i.as_u64()).unwrap_or(0) as usize;
                    mapped.push((id as u32, (k.as_str(), acc_idx)));
                }
            }
            mapped.sort_by_key(|(id, _)| *id);

            for (_, (sem_name, acc_idx)) in &mapped {
                let acc = &accessors[*acc_idx];
                let dims = acc.get("type").and_then(|t| t.as_str()).unwrap_or("VEC3");
                let dim = match dims {
                    "SCALAR" => 1,
                    "VEC2" => 2,
                    "VEC3" => 3,
                    "VEC4" => 4,
                    _ => 3,
                };
                let ctype = acc
                    .get("componentType")
                    .and_then(|c| c.as_u64())
                    .unwrap_or(5126);
                let ty = match ctype {
                    5126 => draco_decoder::AttributeDataType::Float32,
                    5123 => draco_decoder::AttributeDataType::UInt16,
                    5121 => draco_decoder::AttributeDataType::UInt8,
                    5122 => draco_decoder::AttributeDataType::Int16,
                    5120 => draco_decoder::AttributeDataType::Int8,
                    5125 => draco_decoder::AttributeDataType::UInt32,
                    _ => draco_decoder::AttributeDataType::Float32,
                };
                cfg.add_attribute(dim as u32, ty);
                let _ = sem_name;
            }

            let decoded = pollster::block_on(draco_decoder::decode_mesh(data, &cfg))
                .context("draco native decode failed")?;

            let mut off = 0usize;
            let idx_bytes = if index_count <= u16::MAX as u32 {
                (index_count as usize) * 2
            } else {
                (index_count as usize) * 4
            };
            if idx_bytes > 0 {
                let idx_slice = &decoded[off..off + idx_bytes];
                off += idx_bytes;
                if index_count <= u16::MAX as u32 {
                    for c in idx_slice.chunks_exact(2) {
                        indices.push(u16::from_le_bytes([c[0], c[1]]));
                    }
                } else {
                    for c in idx_slice.chunks_exact(4) {
                        let v = u32::from_le_bytes([c[0], c[1], c[2], c[3]]);
                        indices.push(
                            u16::try_from(v)
                                .map_err(|_| anyhow!("decoded index {} exceeds u16", v))?,
                        );
                    }
                }
            }

            // Parse attributes in mapped order; grab POSITION/NORMAL only
            let mut pos_opt: Option<Vec<[f32; 3]>> = None;
            let mut nrm_opt: Option<Vec<[f32; 3]>> = None;
            for (_, (sem_name, acc_idx)) in &mapped {
                let acc = &accessors[*acc_idx];
                let dims = acc.get("type").and_then(|t| t.as_str()).unwrap_or("VEC3");
                let dim = match dims {
                    "SCALAR" => 1usize,
                    "VEC2" => 2usize,
                    "VEC3" => 3usize,
                    "VEC4" => 4usize,
                    _ => 3usize,
                };
                let ctype = acc
                    .get("componentType")
                    .and_then(|c| c.as_u64())
                    .unwrap_or(5126);
                let comp_size = match ctype {
                    5124..=5126 => 4usize,
                    5123 | 5122 => 2usize,
                    5121 | 5120 => 1usize,
                    _ => 4usize,
                };
                let byte_len = dim * (vertex_count as usize) * comp_size;
                let slice = &decoded[off..off + byte_len];
                off += byte_len;

                match (*sem_name, ctype) {
                    ("POSITION", 5126) => {
                        let mut v = Vec::with_capacity(vertex_count as usize);
                        for c in slice.chunks_exact(4 * dim) {
                            let x = f32::from_le_bytes([c[0], c[1], c[2], c[3]]);
                            let y = f32::from_le_bytes([c[4], c[5], c[6], c[7]]);
                            let z = if dim > 2 {
                                f32::from_le_bytes([c[8], c[9], c[10], c[11]])
                            } else {
                                0.0
                            };
                            v.push([x, y, z]);
                        }
                        pos_opt = Some(v);
                    }
                    ("NORMAL", 5126) => {
                        let mut v = Vec::with_capacity(vertex_count as usize);
                        for c in slice.chunks_exact(4 * dim) {
                            let x = f32::from_le_bytes([c[0], c[1], c[2], c[3]]);
                            let y = f32::from_le_bytes([c[4], c[5], c[6], c[7]]);
                            let z = if dim > 2 {
                                f32::from_le_bytes([c[8], c[9], c[10], c[11]])
                            } else {
                                1.0
                            };
                            v.push([x, y, z]);
                        }
                        nrm_opt = Some(v);
                    }
                    _ => {}
                }
            }

            let start = vertices.len();
            let pos = pos_opt.context("decoded POSITION missing")?;
            let nrm = nrm_opt.unwrap_or_else(|| vec![[0.0, 1.0, 0.0]; pos.len()]);
            for i in 0..pos.len() {
                vertices.push(Vertex {
                    pos: pos[i],
                    nrm: nrm[i],
                });
            }
            // Rebase indices for this primitive
            let start_u = start as u32;
            if index_count == 0 {
                for i in 0..(pos.len() as u32) {
                    indices.push((start_u + i) as u16);
                }
            } else {
                let base = indices.len() - (index_count as usize);
                for item in indices.iter_mut().skip(base) {
                    let v = *item as u32 + start_u;
                    *item =
                        u16::try_from(v).map_err(|_| anyhow!("rebased index {} exceeds u16", v))?;
                }
            }
        }
    }

    if vertices.is_empty() || indices.is_empty() {
        bail!("JSON slice: no geometry decoded");
    }
    Ok(CpuMesh { vertices, indices })
}

// Merge a glTF document+buffers into a simple CpuMesh by concatenating
// non‑Draco primitives. If a primitive declares Draco on a target where we
// haven’t already handled it, return an error so callers can fall back.
fn merge_doc_to_cpu(doc: &gltf::Document, buffers: &[gltf::buffer::Data]) -> Result<CpuMesh> {
    let mut vertices: Vec<Vertex> = Vec::new();
    let mut indices: Vec<u16> = Vec::new();
    for mesh in doc.meshes() {
        for prim in mesh.primitives() {
            // If Draco is present here, the caller should have decoded it already
            // (native JSON fallback) or chosen a decompressed asset on wasm.
            if prim.extension_value("KHR_draco_mesh_compression").is_some() {
                bail!("merge_doc_to_cpu: Draco primitive encountered without prior decode");
            }
            let reader = prim.reader(|b| buffers.get(b.index()).map(|bb| bb.0.as_slice()));
            let pos = match reader.read_positions() {
                Some(it) => it.collect::<Vec<[f32; 3]>>(),
                None => continue,
            };
            let nrm: Vec<[f32; 3]> = match reader.read_normals() {
                Some(it) => it.collect(),
                None => vec![[0.0, 1.0, 0.0]; pos.len()],
            };
            let start = vertices.len();
            for i in 0..pos.len() {
                vertices.push(Vertex {
                    pos: pos[i],
                    nrm: nrm[i],
                });
            }
            let start_u = start as u32;
            let indices_read: Vec<u32> = match reader.read_indices() {
                Some(ReadIndices::U16(it)) => it.map(|v| v as u32).collect(),
                Some(ReadIndices::U32(it)) => it.collect(),
                Some(ReadIndices::U8(it)) => it.map(|v| v as u32).collect(),
                None => (0..pos.len() as u32).collect(),
            };
            if indices_read.is_empty() {
                for i in 0..(pos.len() as u32) {
                    indices.push((start_u + i) as u16);
                }
            } else {
                for v in indices_read {
                    let vv = start_u + v;
                    indices.push(
                        u16::try_from(vv)
                            .map_err(|_| anyhow!("rebased index {} exceeds u16", vv))?,
                    );
                }
            }
        }
    }
    if vertices.is_empty() || indices.is_empty() {
        bail!("no geometry found in document");
    }
    Ok(CpuMesh { vertices, indices })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repo_root() -> std::path::PathBuf {
        let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        for _ in 0..5 {
            if p.join("assets/models/wizard.gltf").exists() {
                return p;
            }
            p.pop();
        }
        panic!("could not locate repo root containing assets/models");
    }

    #[test]
    fn load_gltf_mesh_wizard() {
        let root = repo_root();
        let path = root.join("assets/models/wizard.gltf");
        let mesh = load_gltf_mesh(&path).expect("load wizard.gltf");
        assert!(
            !mesh.vertices.is_empty(),
            "wizard vertices should not be empty"
        );
        assert!(
            !mesh.indices.is_empty(),
            "wizard indices should not be empty"
        );
    }

    #[test]
    fn load_gltf_mesh_ruins_draco() {
        let root = repo_root();
        let path = root.join("assets/models/ruins.gltf");
        let mesh = load_gltf_mesh(&path).expect("load ruins.gltf (Draco)");
        assert!(
            !mesh.vertices.is_empty(),
            "ruins vertices should not be empty"
        );
        assert!(
            !mesh.indices.is_empty(),
            "ruins indices should not be empty"
        );
    }
}
