[package]
name = "roa_slice_bevy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bevy = { version = "=0.17", features = ["bevy_ui", "bevy_text"] }
bevy_animation = "=0.17"
bevy_gltf = "=0.17"
clap = { version = "4", features = ["derive"] }
glam = "0.30"
roa_domain = { version = "0.1.0", path = "../../crates/roa_domain" }
