name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Build packs
        run: cargo xtask build-packs
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packs
          path: packs/**

