[package]
name = "sim_core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.9"
rand_chacha = "0.9"
log = "0.4"
data_runtime = { version = "0.1.0", path = "../data_runtime" }
anyhow = "1.0.100"
