[package]
name = "voxel_proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
core_materials = { version = "0.1.0", path = "../core_materials" }
core_units = { version = "0.1.0", path = "../core_units" }
glam = { version = "0.30.8", features = ["serde"] }
